import requests
import json
import os
import re
from datetime import datetime
from typing import Dict, List, Optional, Tuple

# ---------- কনফিগারেশন ----------
HOME_API_URL = "https://www.btvlive.gov.bd/api/home"
# চ্যানেল অনুযায়ী userId API-র URL প্যাটার্ন
USERID_API_PATTERN = "https://www.btvlive.gov.bd/_next/data/wr5BMimBGS-yN5Rc2tmam/channel/{urlname}.json?id={urlname}"
OUTPUT_FILE = "btv_channels.m3u"
# --------------------------------

def fetch_json(url: str, timeout: int = 10) -> Optional[Dict]:
    """যে কোনো URL থেকে JSON ডেটা fetch করে"""
    try:
        print(f"📡 Fetching: {url}")
        response = requests.get(url, timeout=timeout)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.RequestException as e:
        print(f"❌ Error fetching {url}: {e}")
        return None

def get_channels_from_home_api() -> Optional[List[Dict]]:
    """হোম API থেকে সব চ্যানেলের বেসিক তথ্য (identifier, urlname, poster) সংগ্রহ করে"""
    data = fetch_json(HOME_API_URL)
    if not data:
        return None
    
    # হোম API-তে channel_list-এ সব ডিটেইলস আছে
    channels = data.get('channel_list', [])
    if not channels:
        print("❌ No channels found in home API response")
        return None
    
    print(f"✅ Found {len(channels)} channels in home API")
    return channels

def get_user_id_from_channel_api(urlname: str) -> Tuple[Optional[str], Optional[str]]:
    """নির্দিষ্ট চ্যানেলের API থেকে userId এবং userCountry বের করে"""
    # URL তৈরি
    api_url = USERID_API_PATTERN.format(urlname=urlname.replace(' ', '%20'))
    
    data = fetch_json(api_url)
    if not data:
        return None, None
    
    try:
        page_props = data.get('pageProps', {})
        source_url = page_props.get('sourceURL', '')
        user_country = page_props.get('userCountry', 'BD')
        
        # sourceURL থেকে userId বের করা (প্যাটার্ন: .../{userId}/index.m3u8)
        # URL এর শেষ অংশটি userId
        match = re.search(r'/([^/]+)/index\.m3u8$', source_url)
        user_id = match.group(1) if match else None
        
        if user_id:
            print(f"  ✓ {urlname}: userId={user_id}, country={user_country}")
            return user_id, user_country
        else:
            print(f"  ⚠️ {urlname}: Could not extract userId from sourceURL")
            return None, None
            
    except Exception as e:
        print(f"  ❌ Error parsing {urlname} API: {e}")
        return None, None

def generate_m3u_content(channels: List[Dict]) -> str:
    """সব তথ্য একত্রিত করে M3U ফাইল জেনারেট করে"""
    
    content = "#EXTM3U\n"
    content += f"#PLAYLIST: Bangladesh Television Channels (Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')})\n"
    content += "#STATUS: Active\n"
    content += "#LANGUAGE: bn\n\n"
    
    success_count = 0
    failed_channels = []
    
    for channel in channels:
        channel_name = channel.get('channel_name', 'Unknown')
        urlname = channel.get('urlname', '')
        identifier = channel.get('identifier', '')
        poster = channel.get('poster', '')
        
        if not urlname or not identifier:
            print(f"⚠️ Skipping {channel_name}: Missing urlname or identifier")
            failed_channels.append(channel_name)
            continue
        
        # userId এবং userCountry সংগ্রহের জন্য আলাদা API কল
        user_id, user_country = get_user_id_from_channel_api(urlname)
        
        # যদি userId না পাওয়া যায়, তাহলে identifier ব্যাকআপ হিসেবে ব্যবহার করুন
        if not user_id:
            print(f"⚠️ Using identifier as userId for {channel_name}")
            user_id = identifier
            user_country = "BD"  # ডিফল্ট দেশ
        
        # স্ট্রিম URL তৈরি
        stream_url = f"https://www.btvlive.gov.bd/live/{identifier}/{user_country}/{user_id}/index.m3u8"
        
        # EXTINF লাইন - এখন poster URL যোগ করা হয়েছে
        content += f"#EXTINF:-1 tvg-id=\"{identifier}\" tvg-name=\"{channel_name}\" tvg-logo=\"{poster}\" tvg-country=\"BD\" group-title=\"Bangladesh TV\", {channel_name}\n"
        content += f"{stream_url}\n\n"
        
        success_count += 1
        print(f"  ✅ Generated: {channel_name}")
    
    # সারাংশ
    content += f"# Total channels: {success_count}\n"
    content += f"# Generated by: BTV M3U Updater\n"
    
    print(f"\n📊 Summary: {success_count} channels successful, {len(failed_channels)} failed")
    if failed_channels:
        print(f"   Failed: {', '.join(failed_channels)}")
    
    return content

def main():
    print("=" * 70)
    print(f"🚀 BTV M3U Playlist Generator - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 70)
    
    # ধাপ ১: হোম API থেকে সব চ্যানেলের বেসিক তথ্য নিন
    print("\n📥 Step 1: Fetching channel list from home API...")
    channels = get_channels_from_home_api()
    if not channels:
        print("❌ Failed to get channel list. Exiting.")
        raise SystemExit(1)
    
    # ধাপ ২: প্রতিটি চ্যানেলের জন্য userId সংগ্রহ করুন এবং M3U জেনারেট করুন
    print("\n🔍 Step 2: Fetching userId for each channel...")
    m3u_content = generate_m3u_content(channels)
    
    # ধাপ ৩: ফাইল সেভ করুন
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(m3u_content)
    
    # ধাপ ৪: ফাইল ভ্যালিডেশন
    with open(OUTPUT_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        channel_lines = [l for l in lines if l.startswith('#EXTINF')]
    
    print("\n" + "=" * 70)
    print(f"✅ SUCCESS! M3U file updated: {OUTPUT_FILE}")
    print(f"📊 Total channels in playlist: {len(channel_lines)}")
    print(f"📍 File location: {os.path.abspath(OUTPUT_FILE)}")
    print("=" * 70)

if __name__ == "__main__":
    main()
